name: Set End Date on Closed Issues

on:
  issues:
    types: [closed, reopened]

jobs:
  set_end_date:
    runs-on: ubuntu-latest
    steps:
    - name: Check if issue is closed
      if: github.event.action == 'closed'
      run: |
        curl -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"end_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"}' \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
    - name: Check if issue is reopened
      if: github.event.action == 'reopened'
      run: |
        curl -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"end_date": null}' \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
